--------------------------------------------------------
--  Arquivo criado - Sábado-Junho-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_PROG_EBS_PED_VENDA_CAB
--------------------------------------------------------

  CREATE TABLE "INTEGRA"."TB_PROG_EBS_PED_VENDA_CAB" 
   (	"ID_SEQUENCIAL" NUMBER(20,0), 
	"PEDIDO_VENDA_PROGRAMARE" VARCHAR2(50 BYTE), 
	"CODIGO_PEDIDO_ORACLE" NUMBER(20,0), 
	"ORGANIZACAO_VENDA" VARCHAR2(10 BYTE), 
	"NUMERO_ORDEM" VARCHAR2(50 BYTE), 
	"DATA_HORA" TIMESTAMP (6), 
	"TIPO_ORDEM" VARCHAR2(30 BYTE), 
	"ID_VENDEDOR" VARCHAR2(20 BYTE), 
	"NOME_VENDEDOR" VARCHAR2(240 BYTE), 
	"CANAL_VENDAS" VARCHAR2(30 BYTE), 
	"ID_PAGAMENTO" NUMBER(30,0), 
	"DESCRICAO_PAGAMENTO" VARCHAR2(100 BYTE), 
	"ID_REMESSA" VARCHAR2(30 BYTE), 
	"DESCRICAO_REMESSA" VARCHAR2(80 BYTE), 
	"ID_CLIENTE" NUMBER(22,0), 
	"ID_END_CLIENTE_FATU" NUMBER(22,0), 
	"EMPRESA_VENDEDORA" VARCHAR2(10 BYTE), 
	"ID_END_CLIENTE_ENTR" NUMBER(22,0), 
	"MOTIVO_CANC_DEVOL" VARCHAR2(240 BYTE), 
	"OBS" VARCHAR2(300 BYTE), 
	"STATUS_INTEGRACAO" NUMBER(2,0), 
	"DATA_INTEGRACAO" TIMESTAMP (6), 
	"ENVIO_ERRO" VARCHAR2(4000 BYTE), 
	"STATUS_RETORNO" NUMBER(2,0), 
	"DATA_RETORNO" TIMESTAMP (6), 
	"RETORNO_ERRO" VARCHAR2(4000 BYTE), 
	"CODIGO_PBMS" NUMBER(2,0), 
	"CODIGO_PROGRAMA_PBMS" NUMBER(5,0), 
	"PBM_AUTORIZACAO" VARCHAR2(16 BYTE), 
	"PBM_EMPRESA" NUMBER(20,0), 
	"NUM_EMPENHO" VARCHAR2(50 BYTE), 
	"NOME_VENDEDOR_EXTERNO" VARCHAR2(100 BYTE), 
	"NFE" VARCHAR2(20 BYTE), 
	"CHAVE_NFE" VARCHAR2(44 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTEGRACAO" ;
--------------------------------------------------------
--  DDL for Index N1_TB_PROG_EBS_PED_VENDA_CAB
--------------------------------------------------------

  CREATE INDEX "INTEGRA"."N1_TB_PROG_EBS_PED_VENDA_CAB" ON "INTEGRA"."TB_PROG_EBS_PED_VENDA_CAB" ("STATUS_INTEGRACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTEGRACAO" ;
--------------------------------------------------------
--  DDL for Index TB_PROG_EBS_PED_VENDA_CAB_IDX1
--------------------------------------------------------

  CREATE INDEX "INTEGRA"."TB_PROG_EBS_PED_VENDA_CAB_IDX1" ON "INTEGRA"."TB_PROG_EBS_PED_VENDA_CAB" (LPAD("PEDIDO_VENDA_PROGRAMARE",18,'0')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTEGRACAO" ;
--------------------------------------------------------
--  Constraints for Table TB_PROG_EBS_PED_VENDA_CAB
--------------------------------------------------------

  ALTER TABLE "INTEGRA"."TB_PROG_EBS_PED_VENDA_CAB" MODIFY ("ID_SEQUENCIAL" NOT NULL ENABLE);
